apiVersion: apps/v1
kind: Deployment
metadata:
  name: accesscode-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ $.Values.accesscode.replicas }}
  selector:
    matchLabels:
      component: accesscode-service
  template:
    metadata:
      labels:
        component: accesscode-service
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/tls-certificates/grpc-secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Values.accesscode.serviceAccountName }}
      containers:
        - name: accesscode-service
          image: {{ $.Values.accesscode.image }}
          command: ["app"]
          args:
          - "-v=9"
          - "-logtostderr"
          env:
            - name: LOG_LEVEL
              value: {{ $.Values.accesscode.logLevel | quote }}
            - name: HF_NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: GRPC_PORT
              value: "8080"
          ports:
          - containerPort: 8080
          volumeMounts:
          - name: accesscode-secret
            mountPath: "/etc/ssl/certs/ca.crt"
            subPath: ca.crt
            readOnly: true
          - name: accesscode-secret
            mountPath: "/etc/ssl/certs/tls.key"
            subPath: tls.key
            readOnly: true
          - name: accesscode-secret
            mountPath: "/etc/ssl/certs/tls.crt"
            subPath: tls.crt
            readOnly: true
      volumes:
      - name: accesscode-secret
        secret:
          secretName: hobbyfarm-grpc-secret
          optional: false