apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dynamicbindconfigurations.hobbyfarm.io
spec:
  group: hobbyfarm.io
  version: v1
  names:
    kind: DynamicBindConfiguration
    plural: dynamicbindconfigurations
    singular: dynamicbindconfiguration
    shortNames:
    - dbc
  scope: Namespaced
