apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: scenariosessions.hobbyfarm.io
spec:
  group: hobbyfarm.io
  version: v1
  names:
    kind: ScenarioSession
    plural: scenariosessions
    singular: scenariosession
    shortNames:
    - ss
  scope: Cluster