apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: scenarios.hobbyfarm.io
spec:
  group: hobbyfarm.io
  version: v1
  names:
    kind: Scenario
    plural: scenarios
  scope: Cluster