apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sessions.hobbyfarm.io
spec:
  group: hobbyfarm.io
  version: v1
  names:
    kind: Session
    plural: sessions
    singular: session
  scope: Namespaced