apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualmachinesets.hobbyfarm.io
spec:
  group: hobbyfarm.io
  version: v1
  names:
    kind: VirtualMachineSet
    plural: virtualmachinesets
    singular: virtualmachineset
    shortNames:
    - vmset
    - vmsets
  scope: Namespaced
