apiVersion: hobbyfarm.io/v1
kind: DynamicBindConfiguration
metadata:
  name: example-dbc
spec:
  id: example-dbc
  environment: example-environment
  base_name: hf
  restricted_bind: true
  restricted_bind_value: xyz123
  burst_count_capacity:
    ubuntu1604-docker: 2
  burst_capacity:
    cpu: 0
    memory: 0
    storage: 0