{{ if .Values.seed.enabled }}
apiVersion: hobbyfarm.io/v1
kind: Environment
metadata:
  name: example-environment
spec:
  display_name: "Example Environment"
  provider: {{ .Values.terraform.provider }}
  capacity_mode: count
  template_mapping:
    ubuntu1604-docker1:
      image: {{ (index .Values.terraform .Values.terraform.provider).image }}

  environment_specifics:
    executor_image: {{ .Values.terraform.executor.image }}:{{ .Values.terraform.executor.tag }}

    {{ if eq .Values.terraform.provider "ranchervm" }}
{{ toYaml .Values.terraform.ranchervm | indent 4 -}}
    {{ else if eq .Values.terraform.provider "aws" }}
{{ toYaml .Values.terraform.aws | indent 4 -}}
    {{ end }}


  {{ if $.Values.ingress.enabled }}
  ws_endpoint: {{ $.Values.ingress.hostnames.shell | quote }}
  {{ else }}
  ws_endpoint: {{ print "shell." $.Release.Namespace | quote }}
  {{ end }}
  ip_translation_map:
    172.17.2: "184.105.214"
{{ end }}