{{ if $.Values.guac }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
spec:
  selector:
    matchLabels:
      component: guacd
  template:
    metadata:
      labels:
        component: guacd
    spec:
      containers:
        - name: guacd
          image: guacamole/guacd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guac
spec:
  selector:
    matchLabels:
      component: guac
  template:
    metadata:
      labels:
        component: guac
    spec:
      containers:
        - name: guac
          image: {{ $.Values.guac.image }}
{{ end }}
