{{ if $.Values.guac }}
---
apiVersion: v1
kind: Service
metadata:
  name: guac
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    component: guac
  ports:
    - name: http
      port: 80
      targetPort: 4567
{{ end }}
