apiVersion: apps/v1
kind: Deployment
metadata:
  name: gargantua
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      component: gargantua
  template:
    metadata:
      labels:
        component: gargantua
    spec:
      containers:
        - name: gargantua
          image: {{ $.Values.gargantua.image }}
          env:
            - name: LOG_LEVEL
              value: {{$.Values.gargantua.logLevel }}
