---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gargantua
spec:
  selector:
    matchLabels:
      component: gargantua
  template:
    metadata:
      labels:
        component: gargantua
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/tls-certificates/grpc-secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Values.gargantua.serviceAccountName }}
      containers:
        - name: gargantua
          image: {{ $.Values.gargantua.image }}
          command: ["app"]
          args:
            - "-v=9"
            - "-logtostderr"
          env:
            - name: LOG_LEVEL
              value: {{ $.Values.gargantua.logLevel | quote }}
            - name: HF_BASENAME_SCHEDULED_PREFIX
              value: {{ $.Values.gargantua.scheduledBaseNamePrefix | quote }}
            - name: HF_BASENAME_DYNAMIC_PREFIX
              value: {{ $.Values.gargantua.dynamicBaseNamePrefix | quote }}
            - name: HF_NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: PORT
              value: {{ .Values.gargantua.apiPort | quote }}
          ports:
            - containerPort: {{ .Values.gargantua.apiPort }}
          volumeMounts:
          - name: auth-secret
            mountPath: "/etc/ssl/certs/ca.crt"
            subPath: ca.crt
            readOnly: true
          - name: auth-secret
            mountPath: "/etc/ssl/certs/tls.key"
            subPath: tls.key
            readOnly: true
          - name: auth-secret
            mountPath: "/etc/ssl/certs/tls.crt"
            subPath: tls.crt
            readOnly: true
          - name: webhook-secret
            mountPath: "/webhook-secret/ca.crt"
            subPath: ca.crt
            readOnly: true
      volumes:
      - name: auth-secret
        secret:
          secretName: hobbyfarm-grpc-secret
          optional: false
      - name: webhook-secret
        secret:
          secretName: hobbyfarm-webhook-secret
          optional: false